name: Android Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Run unit tests
      run: ./gradlew test
      
    - name: Generate test report
      run: ./gradlew jacocoTestReport
      
    - name: Upload unit test results
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-results
        path: app/build/reports/tests/

  ui-tests:
    runs-on: macos-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Make scripts executable
      run: chmod +x scripts/*.sh
      
    - name: Setup Android Emulator
      run: |
        echo "Setting up Android emulator..."
        ./scripts/setup-emulator.sh
        
    - name: Start Android Emulator
      run: |
        echo "Starting Android emulator..."
        ./scripts/start-emulator.sh &
        
    - name: Wait for Emulator Boot
      run: |
        echo "Waiting for emulator to be ready..."
        timeout 300 bash -c 'until $ANDROID_SDK_ROOT/platform-tools/adb -s emulator-5554 shell getprop sys.boot_completed | grep -q "1"; do sleep 5; done;'
        echo "Emulator is ready!"
        
    - name: Verify Emulator Status
      run: |
        echo "Verifying emulator status..."
        $ANDROID_SDK_ROOT/platform-tools/adb devices
        $ANDROID_SDK_ROOT/platform-tools/adb -s emulator-5554 shell getprop sys.boot_completed
        
    - name: Run UI Tests
      run: |
        echo "Running UI tests..."
        ./gradlew connectedAndroidTest -Pandroid.testInstrumentationRunnerArguments.class=com.pennywise.app.CurrencyUiTestSuite --stacktrace
        
    - name: Stop Emulator
      if: always()
      run: |
        echo "Stopping emulator..."
        ./scripts/stop-emulator.sh
        
    - name: Upload UI test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: ui-test-results
        path: app/build/reports/tests/
        
    - name: Upload emulator logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: emulator-logs
        path: emulator.log
        
    - name: Upload ADB logs
      if: failure()
      run: |
        echo "Collecting ADB logs..."
        $ANDROID_SDK_ROOT/platform-tools/adb logcat -d > adb.log
      uses: actions/upload-artifact@v3
      with:
        name: adb-logs
        path: adb.log

  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Build debug APK
      run: ./gradlew assembleDebug
      
    - name: Build release APK
      run: ./gradlew assembleRelease
      
    - name: Upload APKs
      uses: actions/upload-artifact@v3
      with:
        name: apks
        path: |
          app/build/outputs/apk/debug/
          app/build/outputs/apk/release/
