package com.pennywise.app.presentation.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors - Modern finance palette
val md_theme_light_primary = Color(0xFF4C5D8B)
val md_theme_light_onPrimary = Color(0xFFF6F7FA)
val md_theme_light_primaryContainer = Color(0xFFECEEF4)
val md_theme_light_onPrimaryContainer = Color(0xFF1C1E23)
val md_theme_light_secondary = Color(0xFFF5C400) // Accent
val md_theme_light_onSecondary = Color(0xFF1C1E23)
val md_theme_light_secondaryContainer = Color(0xFFECEEF4)
val md_theme_light_onSecondaryContainer = Color(0xFF1C1E23)
val md_theme_light_tertiary = Color(0xFFF5C400)
val md_theme_light_onTertiary = Color(0xFF1C1E23)
val md_theme_light_tertiaryContainer = Color(0xFFECEEF4)
val md_theme_light_onTertiaryContainer = Color(0xFF1C1E23)
val md_theme_light_error = Color(0xFFC62828)
val md_theme_light_errorContainer = Color(0xFFF6F7FA)
val md_theme_light_onError = Color(0xFFF6F7FA)
val md_theme_light_onErrorContainer = Color(0xFF1C1E23)
val md_theme_light_background = Color(0xFFF6F7FA)
val md_theme_light_onBackground = Color(0xFF1C1E23)
val md_theme_light_surface = Color(0xFFF6F7FA)
val md_theme_light_onSurface = Color(0xFF1C1E23)
val md_theme_light_surfaceVariant = Color(0xFFECEEF4)
val md_theme_light_onSurfaceVariant = Color(0xFF6B7280)
val md_theme_light_outline = Color(0xFF6B7280)
val md_theme_light_inverseOnSurface = Color(0xFFF6F7FA)
val md_theme_light_inverseSurface = Color(0xFF1C1E23)
val md_theme_light_inversePrimary = Color(0xFF9FB1FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4C5D8B)
val md_theme_light_outlineVariant = Color(0xFFECEEF4)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Theme Colors - Modern finance palette
val md_theme_dark_primary = Color(0xFF9FB1FF)
val md_theme_dark_onPrimary = Color(0xFF121318)
val md_theme_dark_primaryContainer = Color(0xFF1E2028)
val md_theme_dark_onPrimaryContainer = Color(0xFFE6E8EF)
val md_theme_dark_secondary = Color(0xFFFFD84D) // Accent
val md_theme_dark_onSecondary = Color(0xFF1C1E23)
val md_theme_dark_secondaryContainer = Color(0xFF1E2028)
val md_theme_dark_onSecondaryContainer = Color(0xFFE6E8EF)
val md_theme_dark_tertiary = Color(0xFFFFD84D)
val md_theme_dark_onTertiary = Color(0xFF1C1E23)
val md_theme_dark_tertiaryContainer = Color(0xFF1E2028)
val md_theme_dark_onTertiaryContainer = Color(0xFFE6E8EF)
val md_theme_dark_error = Color(0xFFEF5350)
val md_theme_dark_errorContainer = Color(0xFF121318)
val md_theme_dark_onError = Color(0xFF121318)
val md_theme_dark_onErrorContainer = Color(0xFFE6E8EF)
val md_theme_dark_background = Color(0xFF121318)
val md_theme_dark_onBackground = Color(0xFFE6E8EF)
val md_theme_dark_surface = Color(0xFF121318)
val md_theme_dark_onSurface = Color(0xFFE6E8EF)
val md_theme_dark_surfaceVariant = Color(0xFF1E2028)
val md_theme_dark_onSurfaceVariant = Color(0xFF9AA0AE)
val md_theme_dark_outline = Color(0xFF9AA0AE)
val md_theme_dark_inverseOnSurface = Color(0xFF121318)
val md_theme_dark_inverseSurface = Color(0xFFE6E8EF)
val md_theme_dark_inversePrimary = Color(0xFF4C5D8B)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF9FB1FF)
val md_theme_dark_outlineVariant = Color(0xFF1E2028)
val md_theme_dark_scrim = Color(0xFF000000)

// Financial Colors
val income_green = Color(0xFF4CAF50)
val expense_red = Color(0xFFC62828)
val neutral_gray = Color(0xFF6B7280)

